#!/usr/bin/env ruby

#Add thor tasks to include path
$:.unshift File.join(File.dirname(__FILE__), 'tasks')

require 'rubygems'
require 'bundler/setup'
Bundler.require(:default)

load 'mrtswath.thor'

Mrtswath.start
